"""Add relay_node to packet_gateway_links.

Revision ID: 5c1c9eb61394
Revises: 75f9edc0b83b
Create Date: 2025-10-04 23:16:15.031953

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c1c9eb61394"
down_revision: str | Sequence[str] | None = "75f9edc0b83b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "packet_gateway_links", sa.Column("relay_node", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("packet_gateway_links", "relay_node")
    # ### end Alembic commands ###
