"""initial schema.

Revision ID: 75f9edc0b83b
Revises:
Create Date: 2025-10-04 18:22:13.400686

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from backend.sa_types import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "75f9edc0b83b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gateways",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_seen", UtcDateTime(), nullable=True),
        sa.Column("last_seen", UtcDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_gateways_id"), "gateways", ["id"], unique=False)
    op.create_index(
        op.f("ix_gateways_last_seen"), "gateways", ["last_seen"], unique=False
    )
    op.create_table(
        "nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_seen", UtcDateTime(), nullable=True),
        sa.Column("last_seen", UtcDateTime(), nullable=True),
        sa.Column("hop_limit", sa.Integer(), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=True),
        sa.Column("legacy", sa.Boolean(), nullable=True),
        sa.Column("position", sa.JSON(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=True),
        sa.Column("info", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_nodes_id"), "nodes", ["id"], unique=False)
    op.create_index(op.f("ix_nodes_last_seen"), "nodes", ["last_seen"], unique=False)
    op.create_table(
        "packets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_id", sa.Integer(), nullable=False),
        sa.Column("to_id", sa.Integer(), nullable=False),
        sa.Column("first_seen", UtcDateTime(), nullable=True),
        sa.Column("length", sa.Integer(), nullable=True),
        sa.Column("hop_start", sa.Integer(), nullable=True),
        sa.Column("portnum", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", "from_id", "to_id"),
    )
    op.create_index(
        op.f("ix_packets_first_seen"), "packets", ["first_seen"], unique=False
    )
    op.create_index(op.f("ix_packets_from_id"), "packets", ["from_id"], unique=False)
    op.create_index(op.f("ix_packets_id"), "packets", ["id"], unique=False)
    op.create_index(op.f("ix_packets_portnum"), "packets", ["portnum"], unique=False)
    op.create_index(op.f("ix_packets_to_id"), "packets", ["to_id"], unique=False)
    op.create_table(
        "direct_links",
        sa.Column("from_node_id", sa.Integer(), nullable=False),
        sa.Column("to_node_id", sa.Integer(), nullable=False),
        sa.Column("last_seen", UtcDateTime(), nullable=True),
        sa.Column("last_snr", sa.Float(), nullable=True),
        sa.Column("last_rssi", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("GATEWAY", "TRACEROUTE", "NEIGHBORINFO", name="linksourceenum"),
            nullable=False,
        ),
        sa.Column("observation_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_node_id"],
            ["nodes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("from_node_id", "to_node_id"),
    )
    op.create_index(
        op.f("ix_direct_links_last_seen"), "direct_links", ["last_seen"], unique=False
    )
    op.create_table(
        "gateway_node_links",
        sa.Column("gateway_id", sa.Integer(), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("last_seen", UtcDateTime(), nullable=True),
        sa.Column("rssi", sa.Integer(), nullable=True),
        sa.Column("snr", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gateway_id"],
            ["gateways.id"],
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["nodes.id"],
        ),
        sa.PrimaryKeyConstraint("gateway_id", "node_id"),
    )
    op.create_table(
        "packet_gateway_links",
        sa.Column("packet_id", sa.Integer(), nullable=False),
        sa.Column("from_id", sa.Integer(), nullable=False),
        sa.Column("to_id", sa.Integer(), nullable=False),
        sa.Column("gateway_id", sa.Integer(), nullable=False),
        sa.Column("seen_at", UtcDateTime(), nullable=True),
        sa.Column("hop_limit", sa.Integer(), nullable=True),
        sa.Column("rssi", sa.Integer(), nullable=True),
        sa.Column("snr", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gateway_id"],
            ["gateways.id"],
        ),
        sa.ForeignKeyConstraint(
            ["packet_id", "from_id", "to_id"],
            ["packets.id", "packets.from_id", "packets.to_id"],
        ),
        sa.PrimaryKeyConstraint("packet_id", "from_id", "to_id", "gateway_id"),
    )
    op.create_index(
        op.f("ix_packet_gateway_links_seen_at"),
        "packet_gateway_links",
        ["seen_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_packet_gateway_links_seen_at"), table_name="packet_gateway_links"
    )
    op.drop_table("packet_gateway_links")
    op.drop_table("gateway_node_links")
    op.drop_index(op.f("ix_direct_links_last_seen"), table_name="direct_links")
    op.drop_table("direct_links")
    op.drop_index(op.f("ix_packets_to_id"), table_name="packets")
    op.drop_index(op.f("ix_packets_portnum"), table_name="packets")
    op.drop_index(op.f("ix_packets_id"), table_name="packets")
    op.drop_index(op.f("ix_packets_from_id"), table_name="packets")
    op.drop_index(op.f("ix_packets_first_seen"), table_name="packets")
    op.drop_table("packets")
    op.drop_index(op.f("ix_nodes_last_seen"), table_name="nodes")
    op.drop_index(op.f("ix_nodes_id"), table_name="nodes")
    op.drop_table("nodes")
    op.drop_index(op.f("ix_gateways_last_seen"), table_name="gateways")
    op.drop_index(op.f("ix_gateways_id"), table_name="gateways")
    op.drop_table("gateways")
    # ### end Alembic commands ###
